### ISSUE TITLE
Value not checked in lossless word conversion

### ISSUE THREAD

**Issue by boeckmann** [VARCem/Vasm#1]
https://github.com/VARCem/Vasm/blob/116aec73ba630face619520ca4e05ba0263efedf/src/expr.c#L601

May be greater than $FFFF if casted from DWORD?

**Comment by waltje** [comment]
> https://github.com/VARCem/Vasm/blob/116aec73ba630face619520ca4e05ba0263efedf/src/expr.c#L601
> 
> May be greater than $FFFF if casted from DWORD?

Fixed in 128dacc, thanks.
